/**
 * Pi hook adapter.
 *
 * Drops a `~/.pi/hooks/before_agent_start.d/vibe-plan-plannotator.sh`
 * shell hook that intercepts the plan emit and forwards it to the
 * vibecontrols agent. Pi reads every `*.sh` from `before_agent_start.d/`,
 * so multiple hooks coexist cleanly.
 */

import {
  mkdir,
  readFile,
  writeFile,
  stat,
  chmod,
  unlink,
} from "node:fs/promises";
import { homedir as osHomedir } from "node:os";

function homedir(): string {
  return osHomedir();
}
import { join, resolve } from "node:path";

import type { AgentAdapter } from "./index.js";

function piDir(): string {
  return join(homedir(), ".pi");
}

function hookDir(): string {
  return join(piDir(), "hooks", "before_agent_start.d");
}

function hookPath(): string {
  return join(hookDir(), "vibe-plan-plannotator.sh");
}

function safeHomePath(path: string): boolean {
  return resolve(path).startsWith(`${homedir()}/`);
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

function buildScript(
  agentApiKey: string,
  agentBaseUrl: string,
  profile: string,
): string {
  const keyEscaped = agentApiKey.replace(/'/g, "'\\''");
  const urlEscaped =
    `${agentBaseUrl}/api/profiles/${profile}/plan/sessions`.replace(
      /'/g,
      "'\\''",
    );
  return `#!/bin/bash
# vibe-plan-plannotator hook — forwards plan content to vibecontrols agent.
# Generated by @vibecontrols/vibe-plugin-plan-plannotator. Do not edit by hand.

set -e
API_KEY='${keyEscaped}'
URL='${urlEscaped}'

if [ -n "$PI_PLAN_FILE" ] && [ -r "$PI_PLAN_FILE" ]; then
  cat "$PI_PLAN_FILE" | curl -sf -X POST \\
    -H 'Content-Type: application/json' \\
    -H "x-agent-api-key: $API_KEY" \\
    --data-binary @- \\
    "$URL" >/dev/null || true
fi
`;
}

export const adapter: AgentAdapter = {
  agent: "pi",
  name: "Pi",
  instructions:
    "Drops a before_agent_start hook into ~/.pi/hooks so Pi plan emits land in plannotator.",

  async detect() {
    const installed = await fileExists(piDir());
    return { installed, configPath: hookPath() };
  },

  async isHookConfigured() {
    return fileExists(hookPath());
  },

  async configureHook({ agentApiKey, agentBaseUrl, profile = "default" }) {
    if (!safeHomePath(hookPath())) {
      throw new Error(`refusing to write outside $HOME: ${hookPath()}`);
    }
    await mkdir(hookDir(), { recursive: true });
    await writeFile(
      hookPath(),
      buildScript(agentApiKey, agentBaseUrl, profile),
      "utf8",
    );
    await chmod(hookPath(), 0o755);
    return { configPath: hookPath() };
  },

  async unconfigureHook() {
    try {
      await unlink(hookPath());
    } catch {
      // Already absent.
    }
  },
};

// Silence unused-import in stricter linters.
void readFile;
